### PR TITLE
Reduce mod size, make Cell Phone cutscene easier to read, CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Dobby233Liu**
> Reduce mod size

By removing (currently) unused audio and graphics and encoding some WAVs to OGGs. We should really gradually add stuff we need to `music/deltarune` instead of copying the whole `mus` folder to the mod. This may break Bor's WIP stuff I'm sorry

Please review if [CONTRIBUTING.md](https://github.com/Dobby233Liu/Dark-Place/blob/warp-bin-refactor/CONTRIBUTING.md) is OK at least before merging.

### CODE REVIEW

**Comment by Dobby233Liu** [comment]
NTS: `git checkout cb6d62f path`

**Comment by Dobby233Liu** [comment]
Anything else ?

**Comment by JustAnotherRandomGithubUser** [comment]
I think it might be good to merge now, yeah.

**Comment by JustAnotherRandomGithubUser** [comment]
(Also, side note, if you're curious as to why all the encoded sound files were so big, it's because I exported them from Audacity. I'm not entirely sure how they got so big, but eh. Any tips on how I can decrease their file size? Just for future reference.)

**Pull request merged**
